### ISSUE TITLE
Build check is failing on the solver-error-classifier repo

### ISSUE THREAD

**Issue by harshad16** [thoth-station/solver-error-classfier#16]
**Describe the bug**

Build check is failing on the solver-error-classifier repo, as the setup.py is point to wrong version file.

```
Requirement already satisfied: yarl==1.6.3 in /opt/app-root/lib/python3.8/site-packages (from -r /tmp/requirements_micropipenv-vq7_kh11.txt (line 2)) (1.6.3)
---> Installing application ...
Processing /opt/app-root/src
  Installing build dependencies: started
  Installing build dependencies: finished with status '\''done'\''
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status '\''error'\''
  ERROR: Command errored out with exit status 1:
   command: /opt/app-root/bin/python3.8 /opt/app-root/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplkot9q8j
       cwd: /tmp/pip-req-build-kqaxrcfc
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/opt/app-root/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/app-root/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['\''return_val'\''] = hook(**hook_input['\''kwargs'\''])
    File "/opt/app-root/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-njkbg01b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-njkbg01b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-njkbg01b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-njkbg01b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, '\''exec'\''), locals())
    File "setup.py", line 88, in <module>
      VERSION = get_version()
    File "setup.py", line 31, in get_version
      with open(os.path.join("template", "version.py")) as f:
  FileNotFoundError: [Errno 2] No such file or directory: '\''template/version.py'\''
```

Related-to: https://github.com/thoth-station/solver-error-classfier/pull/14

**Comment by harshad16** [comment]
This is my mistake, i had moved away some of the files.
