### ISSUE TITLE
sklearn package is out dated and risk prone 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/solver-error-classfier#42]
**Describe the bug**

The sklearn package is out-dated and risk prone
https://github.com/thoth-station/solver-error-classfier/blob/5ae213b99d1694094c34e0f4caaf64c4cba118bc/Pipfile#L15

and the version.py is wrongly referenced:
```
---> Installing application ...
Processing /opt/app-root/src
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/app-root/bin/python3.8 /opt/app-root/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpo5zph994
       cwd: /tmp/pip-req-build-day3da71
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/opt/app-root/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/app-root/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/app-root/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-h7mepsz2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-h7mepsz2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-h7mepsz2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-h7mepsz2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 88, in <module>
      VERSION = get_version()
    File "setup.py", line 31, in get_version
      with open(os.path.join("version.py")) as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'version.py'
```

we ran `thamos advise` and it suggest us to remove it. 
```
~/thoth-station/solver-error-classfier (master) $ thamos advise 
2021-12-10 10:44:08,907 [84033] WARNING  thamos: Development dependencies will not be considered during the resolution process - see https://thoth-station.ninja/j/no_dev
2021-12-10 10:44:08,908 [84033] INFO     thamos.lib: Using Pipenv files to manage dependencies located in '/home/hnalla/thoth-station/solver-error-classfier'
2021-12-10 10:44:08,908 [84033] INFO     thamos.lib: Submitting Pipfile.lock as a base for user's stack scoring - see https://thoth-station.ninja/j/user_stack
2021-12-10 10:44:09,609 [84033] INFO     thamos.lib: Using 'latest' recommendation type - see https://thoth-station.ninja/recommendation-types/
2021-12-10 10:44:09,610 [84033] INFO     thamos.lib: Performing static analysis of sources to gather library usage
2021-12-10 10:44:11,411 [84033] INFO     thamos.lib: Successfully submitted advise analysis 'adviser-211210154410-db2982b6002591ab' to 'https://khemenu.thoth-station.ninja/api/v1'
                                                                         Application stack guidance                                                                          
                                                             ╷                                                                                                  ╷            
  Link                                                       │ Message                                                                                          │ Type       
 ════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════ 
  https://quay.io/repository/thoth-station/ps-nlp            │ Consider using a natural language predictable stack 'ps-nlp' that has prepared environment with  │ ✔️ INFO     
                                                             │ 'nltk'                                                                                           │            
  https://quay.io/repository/thoth-station/ps-nlp-pytorch    │ Consider using a natural language predictable stack 'ps-nlp-pytorch' that has prepared           │ ✔️ INFO     
                                                             │ environment with 'nltk'                                                                          │            
  https://quay.io/repository/thoth-station/ps-nlp-tensorflow │ Consider using a natural language predictable stack 'ps-nlp-tensorflow' that has prepared        │ ✔️ INFO     
                                                             │ environment with 'nltk'                                                                          │            
  https://thoth-station.ninja/j/cve_timestamp                │ CVE database of known vulnerabilities for Python packages was updated at                         │ ✔️ INFO     
                                                             │ '2021-12-10T00:38:23.474791'                                                                     │            
  https://thoth-station.ninja/j/thoth_s2i                    │ It is recommended to use Thoth's s2i to have recommendations specific to runtime environment     │ ✔️ INFO     
  https://thoth-station.ninja/j/rhel_ubi                     │ Using observations for RHEL instead of UBI, RHEL is ABI compatible with UBI                      │ ⚠️ WARNING  
  https://thoth-station.ninja/recommendation-types/          │ Using recommendation type 'latest'                                                               │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ Resolving for runtime environment named 'ubi8'                                                   │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ Resolving for operating system 'rhel' in version '8'                                             │ -          
  https://thoth-station.ninja/j/env                          │ Resolving for Python version '3.8'                                                               │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ Using platform 'linux-x86_64'                                                                    │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ No constraints supplied to the resolution process                                                │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ Using supplied static source code analysis                                                       │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ No containerized environment used                                                                │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ Using CPU family 'UNKNWON' model 'UNKNOWN'                                                       │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ No CUDA used                                                                                     │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ No cuDNN used                                                                                    │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ No OpenBLAS used                                                                                 │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ No OpenMPI used                                                                                  │ ✔️ INFO     
  https://thoth-station.ninja/j/env                          │ No MKL used                                                                                      │ ✔️ INFO     
  https://thoth-station.ninja/j/eol_env                      │ Runtime environment used is no longer supported, it is recommended to switch to another runtime  │ ⚠️ WARNING  
                                                             │ environment                                                                                      │            
  https://thoth-station.ninja/j/prescription                 │ Using prescriptions 'thoth' release 'v0.12.0'                                                    │ ✔️ INFO     
  https://github.com/thoth-station/prescriptions             │ Using resolver prescriptions from thoth-station/prescriptions                                    │ ✔️ INFO     
  https://thoth-station.ninja/j/no_cpu                       │ No CPU model provided, please state CPU model in your .thoth.yaml configuration file to have     │ ⚠️ WARNING  
                                                             │ recommendations optimized for your runtime environment                                           │            
  https://thoth-station.ninja/j/no_cpu                       │ No CPU family provided, please state CPU family in your .thoth.yaml configuration file to have   │ ⚠️ WARNING  
                                                             │ recommendations optimized for your runtime environment                                           │            
  https://thoth-station.ninja/j/rules                        │ Removing package 'click' in versions '<=6.6' from index 'https://pypi.org/simple' based on rule: │ ⚠️ WARNING  
                                                             │ Package released before December 2016                                                            │            
  https://thoth-station.ninja/j/rules                        │ Removing package 'matplotlib' in versions '<=2.0.0b4' from index 'https://pypi.org/simple' based │ ⚠️ WARNING  
                                                             │ on rule: Package released before December 2016                                                   │            
  https://thoth-station.ninja/j/rules                        │ Removing package 'nltk' in versions '<=3.2.1' from index 'https://pypi.org/simple' based on      │ ⚠️ WARNING  
                                                             │ rule: Package released before December 2016                                                      │            
  https://thoth-station.ninja/j/rules                        │ Removing package 'pyyaml' in versions '<=3.12' from index 'https://pypi.org/simple' based on     │ ⚠️ WARNING  
                                                             │ rule: Package released before December 2016                                                      │            
  https://thoth-station.ninja/j/rules                        │ Removing package 'requests' in versions '<=2.12.2' from index 'https://pypi.org/simple' based on │ ⚠️ WARNING  
                                                             │ rule: Package released before December 2016                                                      │            
  https://thoth-station.ninja/j/rules                        │ Removing package 'sklearn' in versions '<=0.0' from index 'https://pypi.org/simple' based on     │ ⚠️ WARNING  
                                                             │ rule: Package released before December 2016                                                      │            
  https://thoth-station.ninja/j/unresolved                   │ Cannot satisfy direct dependencies: direct dependencies of type 'sklearn' were removed by        │ ❌ ERROR   
                                                             │ pipeline sieves                                                                                  │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'click' from                                                           │ ⚠️ WARNING  
                                                             │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were removed due   │            
                                                             │ to installation issues in the target environment: 8.0.2                                          │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'matplotlib' from 'https://pypi.org/simple' were removed due to        │ ⚠️ WARNING  
                                                             │ installation issues in the target environment: 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.1, 1.3.0, 1.2.1,  │            
                                                             │ 1.2.0, 1.1.1, 1.1.0, 1.0.1, 1.0.0, 0.99.3, 0.99.1, 0.99.0, 0.98.5.3, 0.98.5.1, 0.98.3, 0.98.1,   │            
                                                             │ 0.98.0, 0.91.4, 0.91.3, 0.91.2, 0.91.1, 0.91.0, 0.90.1, 0.90.0, 0.87.7, 0.87.6, 0.87.5, 0.87.4,  │            
                                                             │ 0.87.3, 0.87.2, 0.87.1, 0.86.2, 0.86.1, 0.86, 0.85, 0.83.2, 0.71, 0.70, 0.65, 0.64, 0.63.0       │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'matplotlib' from                                                      │ ⚠️ WARNING  
                                                             │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were removed due   │            
                                                             │ to installation issues in the target environment: 3.3.0, 3.1.2, 3.1.0, 3.0.2, 3.0.1, 2.2.5,      │            
                                                             │ 2.2.3, 2.2.2, 2.1.1                                                                              │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'nltk' from 'https://pypi.org/simple' were removed due to installation │ ⚠️ WARNING  
                                                             │ issues in the target environment: 3.3, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 0.9.9, 0.9.8, 0.9.7,   │            
                                                             │ 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9, 0.8                                                             │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'nltk' from                                                            │ ⚠️ WARNING  
                                                             │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were removed due   │            
                                                             │ to installation issues in the target environment: 3.6.1, 3.5, 3.4.2, 3.4.1, 3.2, 3.0.2, 3.0.1,   │            
                                                             │ 0.9.9, 0.9.8, 0.9, 0.8                                                                           │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'numpy' from 'https://pypi.org/simple' were removed due to             │ ⚠️ WARNING  
                                                             │ installation issues in the target environment: 1.17.2, 1.17.1, 1.17.0, 1.16.6, 1.16.5, 1.16.4,   │            
                                                             │ 1.16.3, 1.16.2, 1.16.1, 1.16.0, 1.15.4, 1.15.3, 1.14.6, 1.14.2, 1.14.1, 1.14.0, 1.13.3, 1.13.1,  │            
                                                             │ 1.13.0, 1.12.1, 1.12.0, 1.11.3, 1.11.2, 1.11.1, 1.11.0, 1.10.4, 1.10.3, 1.10.2, 1.10.1, 1.10.0,  │            
                                                             │ 1.9.3, 1.9.2, 1.9.1, 1.9.0, 1.8.2, 1.8.1, 1.8.0, 1.7.2, 1.7.1, 1.7.0, 1.6.2, 1.6.1, 1.6.0,       │            
                                                             │ 1.5.1, 1.5.0, 1.4.1, 1.4.0, 1.3.0, 1.2.1, 1.2.0, 1.1.1, 1.0.4, 1.0.3, 1.0, 0.9.8, 0.9.6          │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'numpy' from                                                           │ ⚠️ WARNING  
                                                             │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were removed due   │            
                                                             │ to installation issues in the target environment: 1.17.5, 1.13.3                                 │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'pandas' from 'https://pypi.org/simple' were removed due to            │ ⚠️ WARNING  
                                                             │ installation issues in the target environment: 0.25.1, 0.25.0, 0.24.2, 0.24.1, 0.24.0, 0.23.4,   │            
                                                             │ 0.23.3, 0.23.2, 0.23.1, 0.23.0, 0.22.0, 0.21.1, 0.21.0, 0.20.3, 0.20.2, 0.20.1, 0.20.0, 0.19.2,  │            
                                                             │ 0.19.1, 0.19.0, 0.18.1, 0.18.0, 0.17.1, 0.17.0, 0.16.2, 0.16.1, 0.16.0, 0.15.2, 0.15.1, 0.15.0,  │            
                                                             │ 0.14.1, 0.14.0, 0.13.1, 0.13.0, 0.12.0, 0.11.0, 0.10.1, 0.10.0, 0.9.1, 0.9.0, 0.8.1, 0.8.0,      │            
                                                             │ 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.1, 0.6.0, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2, 0.1     │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'pandas' from                                                          │ ⚠️ WARNING  
                                                             │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were removed due   │            
                                                             │ to installation issues in the target environment: 1.3.4, 1.2.4, 0.20.2                           │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'requests' from 'https://pypi.org/simple' were removed due to          │ ⚠️ WARNING  
                                                             │ installation issues in the target environment: 2.15.0, 0.14.2, 0.12.1, 0.10.0, 0.9.3, 0.9.2,     │            
                                                             │ 0.9.1, 0.9.0, 0.8.9, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.6,       │            
                                                             │ 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6.0,       │            
                                                             │ 0.5.1, 0.5.0, 0.4.1, 0.4.0, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.0.1                      │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'requests' from                                                        │ ⚠️ WARNING  
                                                             │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were removed due   │            
                                                             │ to installation issues in the target environment: 2.15.1, 2.14.2                                 │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'scipy' from 'https://pypi.org/simple' were removed due to             │ ⚠️ WARNING  
                                                             │ installation issues in the target environment: 1.3.1, 1.3.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.0,  │            
                                                             │ 1.0.1, 1.0.0, 0.19.1, 0.19.0, 0.18.1, 0.18.0, 0.17.1, 0.17.0, 0.16.1, 0.16.0, 0.15.1, 0.15.0,    │            
                                                             │ 0.14.1, 0.14.0, 0.13.3, 0.13.2, 0.13.1, 0.13.0, 0.12.1, 0.12.0, 0.11.0, 0.10.1, 0.10.0, 0.9.0,   │            
                                                             │ 0.8.0, 0.7.2, 0.7.0, 0.6.0, 0.5.2, 0.4.4                                                         │            
  https://thoth-station.ninja/j/install_error                │ The following versions of 'scipy' from                                                           │ ⚠️ WARNING  
                                                             │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were removed due   │            
                                                             │ to installation issues in the target environment: 1.5.1, 1.0.0                                   │            
                                                             ╵                                                                                                  ╵            
                                  Cannot satisfy direct dependencies: direct dependencies of type 'sklearn' were removed by pipeline sieves 
```

**Comment by harshad16** [comment]
This commit fixes this issue: https://github.com/thoth-station/solver-error-classfier/commit/8c6acda9c273ae1bd82672fbb0bb696c06e6e6f4
